# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /users
    controller: 'funcionListadoUsuarios'
    methods:
      - GET

ruta_result_list:
    path: /results
    controller: 'funcionListadoResultados'
    methods:
        - GET

ruta_read_user_form:
    path: /read/user
    controller: 'funcionReadUserForm'
    methods:
        - GET
        - POST

ruta_create_user_form:
    path: /create/user
    controller: 'funcionCreateUserForm'
    methods:
        - GET
        - POST
        -
ruta_delete_user_form:
    path: /delete/user
    controller: 'funcionDeleteUserForm'
    methods:
        - GET
        - POST

ruta_update_user_form:
    path: /update/user
    controller: 'funcionUpdateUserForm'
    methods:
        - GET
        - POST

ruta_read_result_form:
    path: /read/result
    controller: 'funcionReadResultForm'
    methods:
        - GET
        - POST

ruta_create_result_form:
    path: /create/result
    controller: 'funcionCreateResultForm'
    methods:
        - GET
        - POST

ruta_user:
    path:     /users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE